
DEFINE QUERY q1 FOR customer SCROLLING.
DEFINE BUTTON btn_1 LABEL "Next". 
DEFINE BUTTON btn_2 LABEL "Prev".
DEFINE BROWSE b1 QUERY q1 DISPLAY custnum NAME balance
WITH 10 DOWN SEPARATORS
TITLE "Customer List".
DEFINE FRAME f1
b1
WITH SIDE-LABELS ROW 2 CENTERED NO-BOX.
OPEN QUERY q1 FOR EACH customer NO-LOCK.
ENABLE ALL WITH FRAME f1. 
WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.

